// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'us-west-2',
  'aws_cognito_identity_pool_id': 'us-west-2:1585fa50-9b0c-4710-b620-aea564b75a34',
  'aws_cognito_region': 'us-west-2',
  'aws_user_pools_id': 'us-west-2_s0DDQenJO',
  'aws_user_pools_web_client_id': '6e3mkqd549k3p6rkm2fefk98ai',
  'aws_appsync_graphqlEndpoint': 'https://osyv5ee7dvfxrlhw75xnce6fpe.appsync-api.us-west-2.amazonaws.com/graphql',
  'aws_appsync_region': 'us-west-2',
  'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS'
}

export default awsmobile
