// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import Secrets from 'react-native-config'

const awsmobile = {
  'aws_cognito_region': 'us-west-2',
  'aws_appsync_graphqlEndpoint': Secrets.GRAPHQL,
  'aws_appsync_region': 'us-west-2',
  'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
  'aws_app_analytics': 'enable',
  'aws_cognito_identity_pool_id': Secrets.COGNITOPOOLID,
  'aws_cognito_region': 'us-west-2',
  'aws_content_delivery': 'enable',
  'aws_content_delivery_bucket': Secrets.DEVBUCKET,
  'aws_content_delivery_bucket_region': 'us-west-1',
  'aws_content_delivery_cloudfront': 'enable',
  'aws_content_delivery_cloudfront_domain': Secrets.CLOUDFRONT,
  'aws_mobile_analytics_app_id': Secrets.ANALYTICS,
  'aws_mobile_analytics_app_region': 'us-east-1',
  'aws_project_id': Secrets.PROJECTID,
  'aws_project_name': 'GeoGraffiti-2018-09-21-16-30-25',
  'aws_project_region': 'us-west-1',
  'aws_resource_name_prefix': 'geograffiti-mobilehub-2140603857',
  'aws_sign_in_enabled': 'enable',
  'aws_user_pools': 'enable',
  'aws_user_pools_id': Secrets.USERPOOLID,
  'aws_user_pools_mfa_type': 'ON',
  'aws_user_pools_web_client_id': Secrets.WEBPOOL,
}

export default awsmobile
